# Generated by Django 5.0.2 on 2025-05-04 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrateur',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('idClientApprouveCommeVendeur', models.JSONField(default=list)),
                ('idNouveauxClientsInscrits', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='ArticleCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commande_id', models.IntegerField()),
                ('produit_id', models.IntegerField()),
                ('prix_achat', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='ArticlePanier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('panier_id', models.IntegerField()),
                ('produit_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('num_carte', models.CharField(blank=True, max_length=50, null=True)),
                ('nom_carte', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utilisateur_id', models.IntegerField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(default='en_attente', max_length=20)),
                ('montant_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commande_id', models.IntegerField()),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('methode_paiement', models.CharField(max_length=50)),
                ('statut', models.CharField(choices=[('effectuee', 'Effectuée'), ('en_attente', 'En attente')], max_length=20, null=True)),
                ('date_paiement', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Panier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utilisateur_id', models.IntegerField()),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProduitNFT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.BinaryField(blank=True, null=True)),
                ('nom', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('proprietaire', models.IntegerField()),
                ('prix', models.DecimalField(decimal_places=2, max_digits=12)),
                ('categorie', models.CharField(choices=[('artistique', 'Artistique'), ('musicale', 'Musicale'), ('gamming', 'Gaming')], max_length=50)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('certification', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acheteur', models.IntegerField(blank=True, null=True)),
                ('vendeur', models.IntegerField(blank=True, null=True)),
                ('produit', models.IntegerField(blank=True, null=True)),
                ('montant', models.FloatField()),
                ('statut', models.CharField(choices=[('validee', 'Validée'), ('refusee', 'Refusée'), ('en_attente', 'En attente')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionPaiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.IntegerField()),
                ('paiement_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('statut', models.CharField(choices=[('visiteur', 'Visiteur'), ('client', 'Client'), ('vendeur', 'Vendeur'), ('admin', 'Admin')], default='visiteur', max_length=20)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vendeur',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='metasouk.utilisateur')),
                ('revenu_total', models.FloatField(default=0)),
            ],
        ),
    ]
