# Generated by Django 5.0.2 on 2025-05-05 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metasouk', '0002_remove_transaction_produit_client_age_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='age',
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='mot_de_passe_carte',
            field=models.CharField(default='0000', max_length=100),
        ),
    ]
