# Generated by Django 5.0.2 on 2025-05-08 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metasouk', '0004_delete_client_utilisateur_nom_utilisateur_prenom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produitnft',
            name='image_data',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='produitnft',
            name='categorie',
            field=models.CharField(choices=[('artistique', 'Artistique'), ('musicale', 'Musicale'), ('gaming', 'Gaming')], max_length=50),
        ),
        migrations.AlterField(
            model_name='produitnft',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='nft_images/'),
        ),
    ]
