# Generated by Django 5.0.2 on 2025-05-09 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metasouk', '0005_produitnft_image_data_alter_produitnft_categorie_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlepanier',
            name='panier_id',
        ),
        migrations.RemoveField(
            model_name='articlepanier',
            name='produit_id',
        ),
        migrations.AddField(
            model_name='articlepanier',
            name='panier',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='metasouk.panier'),
        ),
        migrations.AddField(
            model_name='articlepanier',
            name='produit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='metasouk.produitnft'),
        ),
        migrations.AddField(
            model_name='panier',
            name='session_key',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='produitnft',
            name='image',
            field=models.ImageField(default='nft_images/default.jpg', upload_to='nft_images/'),
        ),
    ]
