# Generated by Django 5.0.2 on 2025-05-09 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metasouk', '0006_remove_articlepanier_panier_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produitnft',
            name='proprietaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metasouk.utilisateur'),
        ),
    ]
