# Generated by Django 5.0.2 on 2025-05-10 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metasouk', '0007_alter_produitnft_proprietaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='produitnft',
            name='est_vendu',
            field=models.BooleanField(default=False),
        ),
    ]
