# Generated by Django 5.0.2 on 2025-05-10 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metasouk', '0008_produitnft_est_vendu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlecommande',
            name='commande_id',
        ),
        migrations.RemoveField(
            model_name='articlecommande',
            name='produit_id',
        ),
        migrations.AddField(
            model_name='articlecommande',
            name='commande',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='metasouk.commande'),
        ),
        migrations.AddField(
            model_name='articlecommande',
            name='produit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='metasouk.produitnft'),
        ),
    ]
