# Generated by Django 5.0.2 on 2025-05-10 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metasouk', '0010_alter_commande_utilisateur_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commande',
            old_name='utilisateur_id',
            new_name='utilisateur',
        ),
    ]
