# Generated by Django 5.0.2 on 2025-05-10 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metasouk', '0011_rename_utilisateur_id_commande_utilisateur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='panier',
            name='utilisateur_id',
        ),
        migrations.AddField(
            model_name='panier',
            name='utilisateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='metasouk.utilisateur'),
        ),
    ]
