# Generated by Django 5.0.2 on 2025-05-10 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metasouk', '0012_remove_panier_utilisateur_id_panier_utilisateur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='panier',
            name='session_key',
        ),
    ]
