# Generated by Django 5.0.2 on 2025-05-11 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metasouk', '0013_remove_panier_session_key'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendeur',
            old_name='id',
            new_name='utilisateur',
        ),
    ]
