# Generated by Django 5.0.2 on 2025-05-11 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metasouk', '0014_rename_id_vendeur_utilisateur'),
    ]

    operations = [
        migrations.RenameField(
            model_name='administrateur',
            old_name='id',
            new_name='utilisateur',
        ),
    ]
