# Generated by Django 5.0.2 on 2025-05-11 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metasouk', '0015_rename_id_administrateur_utilisateur'),
    ]

    operations = [
        migrations.RenameField(
            model_name='administrateur',
            old_name='idNouveauxClientsInscrits',
            new_name='clients_demandant_vente',
        ),
    ]
